#!/usr/bin/env python3
"""Generate a human-readable sync report from discovery and upstream check results."""
from __future__ import annotations

import argparse
import json
import os
import sys
import re
from datetime import UTC, datetime
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]


def escape_table_cell(value: object) -> str:
    return str(value or "").replace("|", "\\|").replace("\n", " ").strip()


def source_label(discovery: dict) -> str:
    source = discovery.get("source") or discovery.get("source_repo") or "source"
    url = discovery.get("url") or ""
    repo = discovery.get("source_repo") or ""
    if not repo:
        match = re.search(r"\(([^)]+/[^)]+)\)", str(source))
        if match:
            repo = match.group(1)
    label = repo or source
    if url:
        return f"[{escape_table_cell(label)}]({url})"
    if repo:
        return f"[{escape_table_cell(repo)}](https://github.com/{repo})"
    return escape_table_cell(label)


def upstream_skill_name(row: dict) -> str:
    return (
        row.get("skill_name")
        or row.get("video_name")
        or row.get("slug")
        or Path(row.get("repo_skill", "")).parent.name
        or "unknown-skill"
    )


def upstream_update_reason(row: dict) -> str:
    if row.get("update_reason"):
        return row["update_reason"]
    latest = row.get("latest_commit")
    if latest:
        return f"new upstream commit `{latest[:12]}` available"
    return "new commits available"


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate sync report.")
    parser.add_argument("--discovery", default="docs/sources/reports/discovery.json")
    parser.add_argument("--upstream", default="docs/sources/reports/upstream-check.json")
    parser.add_argument("--output", default="docs/sources/reports/sync-report.md")
    args = parser.parse_args()
    
    discovery_path = REPO_ROOT / args.discovery
    upstream_path = REPO_ROOT / args.upstream
    output_path = REPO_ROOT / args.output
    
    # Load data
    discovery = {}
    if discovery_path.exists():
        discovery = json.loads(discovery_path.read_text(encoding="utf-8"))
    
    upstream = {}
    if upstream_path.exists():
        upstream = json.loads(upstream_path.read_text(encoding="utf-8"))
    
    new_skills = discovery.get("discoveries", [])
    upstream_updates = [r for r in upstream.get("rows", []) if r.get("needs_update")]
    
    has_updates = bool(new_skills or upstream_updates)
    
    # Set GitHub Actions output
    github_output = os.environ.get("GITHUB_OUTPUT")
    if github_output:
        with open(github_output, "a") as f:
            f.write(f"has_updates={'true' if has_updates else 'false'}\n")
    
    # Generate report
    lines = [
        f"# Weekly Skill Sync Report",
        f"",
        f"**Generated**: {datetime.now(UTC).strftime('%Y-%m-%d %H:%M UTC')}",
        f"**Local skills**: {discovery.get('local_skill_count', 'N/A')}",
        f"",
    ]
    
    if new_skills:
        lines.append(f"## New Skills Discovered ({len(new_skills)})")
        lines.append("")
        lines.append("| Skill | Source | Stars/Installs | Description |")
        lines.append("|-------|-----------|-------|-------------|")
        for s in new_skills[:30]:  # Cap at 30
            name = escape_table_cell(s.get("name", ""))
            source = source_label(s)
            stars = s.get("repo_stars", 0)
            desc = escape_table_cell(s.get("description") or s.get("repo_description") or "")[:120]
            lines.append(f"| `{name}` | {source} | {stars} | {desc} |")
        lines.append("")
    
    if upstream_updates:
        lines.append(f"## Upstream Updates ({len(upstream_updates)})")
        lines.append("")
        for u in upstream_updates:
            lines.append(f"- **{upstream_skill_name(u)}**: {upstream_update_reason(u)}")
        lines.append("")
    
    if not has_updates:
        lines.append("No new discoveries or upstream updates this week. All skills are up to date.")
        lines.append("")
    
    lines.append("---")
    lines.append("*This report was auto-generated by the [upstream-sync workflow](.github/workflows/upstream-sync.yml).*")
    
    report = "\n".join(lines)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(report, encoding="utf-8")
    print(f"Wrote sync report: {output_path}")
    if has_updates:
        print(f"Updates found: {len(new_skills)} new skills, {len(upstream_updates)} upstream updates")
    else:
        print("No updates found.")


if __name__ == "__main__":
    main()
